# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ry < Formula
  desc "Agentic terminal multiplexer for code development"
  homepage "https://rysh.ai"
  version "0.2.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://packages.rysh.ai/releases/v0.2.9/ry_darwin_amd64.tar.gz"
      sha256 "b171ed5bf3c0eebd9435cbdf60810bfae6d6c7bc4654a46e74d5a2f0c9c4856f"

      define_method(:install) do
        bin.install "ry"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
    if Hardware::CPU.arm?
      url "https://packages.rysh.ai/releases/v0.2.9/ry_darwin_arm64.tar.gz"
      sha256 "c3690a95da214474adf2f10e849933489bb90ee8ac80c6bdb4f81a34f1e83477"

      define_method(:install) do
        bin.install "ry"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://packages.rysh.ai/releases/v0.2.9/ry_linux_amd64.tar.gz"
      sha256 "61a1b033cb67c3e47333850cfe030139fdd3e3b6ccb07db2db6e768821b9f895"
      define_method(:install) do
        bin.install "ry"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://packages.rysh.ai/releases/v0.2.9/ry_linux_arm64.tar.gz"
      sha256 "6f75031cc819b9dac18ffabfc605487f512276fa85ae4053b42b4518f0c3c945"
      define_method(:install) do
        bin.install "ry"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
  end

  test do
    system "#{bin}/ry", "--version"
  end
end
