# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ry < Formula
  desc "Agentic terminal multiplexer for code development"
  homepage "https://rysh.ai"
  version "0.2.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://packages.rysh.ai/releases/v0.2.5/ry_darwin_amd64.tar.gz"
      sha256 "b7899144b5fedadc0562038ff5ec5f352ce0f5273dc7eec6701f9853642b9dc4"

      define_method(:install) do
        bin.install "ry"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
    if Hardware::CPU.arm?
      url "https://packages.rysh.ai/releases/v0.2.5/ry_darwin_arm64.tar.gz"
      sha256 "5bee566ff2a736bb8eeb50288761cb45f146d7adf037ee541a9436c554e4a920"

      define_method(:install) do
        bin.install "ry"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://packages.rysh.ai/releases/v0.2.5/ry_linux_amd64.tar.gz"
      sha256 "afff38d33334d9ff7f90eaee40270e6478c476dd3a36a97ba2300ed9850381de"
      define_method(:install) do
        bin.install "ry"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://packages.rysh.ai/releases/v0.2.5/ry_linux_arm64.tar.gz"
      sha256 "2d52772280c157293360ae539b9e16913be59d6f8b4691d68f76907d20fda033"
      define_method(:install) do
        bin.install "ry"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
  end

  test do
    system "#{bin}/ry", "--version"
  end
end
