# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rysh < Formula
  desc "Agentic terminal multiplexer for code development"
  homepage "https://github.com/rysh-ai/rysh-cli-parent"
  version "0.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rysh-ai/rysh-cli-code/releases/download/v0.2.6/rysh_darwin_amd64.tar.gz"
      sha256 "c9a18533fd5c6f3dd96178ce48b6dd35dc0a174cb2138c342fb251f290b3c4cb"

      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rysh-ai/rysh-cli-code/releases/download/v0.2.6/rysh_darwin_arm64.tar.gz"
      sha256 "1170d7614f2f44db086c0077f3815426f741ea048ed7a8ac6989a2b1627c4b73"

      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rysh-ai/rysh-cli-code/releases/download/v0.2.6/rysh_linux_amd64.tar.gz"
      sha256 "d237b6761dcdc6c436b329fdd3ea434b20f73520d8871e89c7e62c93e39d652e"
      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rysh-ai/rysh-cli-code/releases/download/v0.2.6/rysh_linux_arm64.tar.gz"
      sha256 "e505832b165c7330b060f931ae1369682cfbf8b71c8f7d687367584ec37822ce"
      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
  end

  test do
    system "#{bin}/rysh", "--version"
  end
end
