# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rysh < Formula
  desc "Agentic terminal multiplexer for code development"
  homepage "https://rysh.ai"
  version "0.1.20"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://packages.rysh.ai/releases/v0.1.20/rysh_darwin_amd64.tar.gz"
      sha256 "947a2366609a8030e0aa6a3bc819d0d57c4e40e6f57a4a9c2c68c49a81366c0b"

      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
    if Hardware::CPU.arm?
      url "https://packages.rysh.ai/releases/v0.1.20/rysh_darwin_arm64.tar.gz"
      sha256 "a2fe4417b31b1ac15874144248b40c0405fa464e0c81fa29f4bfe91cef1cb929"

      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://packages.rysh.ai/releases/v0.1.20/rysh_linux_amd64.tar.gz"
      sha256 "40e5e0c3460e4e0b542143fcad5763deccce6f48b609c913f2bc30f037c306e6"
      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://packages.rysh.ai/releases/v0.1.20/rysh_linux_arm64.tar.gz"
      sha256 "207ae7236363f07afa50b9cb47c2a23e902c09f883170a01c3070941db5b04b2"
      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.yaml.example" => "rysh/rysh.config.yaml.example"
      end
    end
  end

  test do
    system "#{bin}/rysh", "--version"
  end
end
