# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rysh < Formula
  desc "Agentic terminal multiplexer for code development"
  homepage "https://rysh.ai"
  version "0.1.9"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://packages.rysh.ai/releases/v0.1.9/rysh_darwin_amd64.tar.gz"
      sha256 "21c5fdc052b4059ad6d75cb92ec6521b11e52a8e44cbf96397aba988902a92ee"

      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.example" => "rysh/rysh.config.example"
      end
    end
    if Hardware::CPU.arm?
      url "https://packages.rysh.ai/releases/v0.1.9/rysh_darwin_arm64.tar.gz"
      sha256 "cae67e63777e432a04ef03e2bc552153640031bbe511e37ed2c621a97d71e19e"

      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.example" => "rysh/rysh.config.example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://packages.rysh.ai/releases/v0.1.9/rysh_linux_amd64.tar.gz"
      sha256 "b9e6ddcb463b346b088aaadc5508838f272e6ff377cca15f61c5efa20c55eb0f"
      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.example" => "rysh/rysh.config.example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://packages.rysh.ai/releases/v0.1.9/rysh_linux_arm64.tar.gz"
      sha256 "9b778a994c71657cf0283b3e55949d9730ef74a812240703df8fbe47302cc338"
      define_method(:install) do
        bin.install "rysh"
        mkdir_p etc/"rysh"
        etc.install "rysh.config.example" => "rysh/rysh.config.example"
      end
    end
  end

  test do
    system "#{bin}/rysh", "--version"
  end
end
